---
- name: Install packages!
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ my_packages }}"

#- name: Create symbolic link
#  file:
#    src: "{{ source_folder }}"
#    dest: "/usr/src/linux"
#    state: link
#
#- name: Remove packages
#  package:
#    name: "{{ item }}"
#    state: absent
#  with_items:
#    - nano
#

- import_tasks: commands.yml
...
